[CmdletBinding()]
param(
    [string]$PythonExe = "",
    [string]$MSInstallRoot = "",
    [string]$DefaultOutputRoot = "",
    [ValidateRange(1, 4096)]
    [int]$DefaultCores = 48,
    [switch]$SkipMSCheck
)

$ErrorActionPreference = "Stop"
$skillRoot = Split-Path -Parent $PSScriptRoot
$configDir = Join-Path $skillRoot "config"
$configFile = Join-Path $configDir "pl-skill.local.bat"

function Resolve-PythonExecutable {
    param([string]$Requested)

    if ($Requested) {
        if (Test-Path -LiteralPath $Requested -PathType Leaf) {
            return (Resolve-Path -LiteralPath $Requested).Path
        }
        $command = Get-Command $Requested -ErrorAction SilentlyContinue
        if ($command) {
            return $command.Source
        }
        throw "Requested Python executable was not found: $Requested"
    }

    foreach ($name in @("python.exe", "python3.exe", "python")) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($command) {
            return $command.Source
        }
    }

    $launcher = Get-Command "py.exe" -ErrorAction SilentlyContinue
    if ($launcher) {
        $resolved = & $launcher.Source -3 -c "import sys; print(sys.executable)"
        if ($LASTEXITCODE -eq 0 -and $resolved -and
            (Test-Path -LiteralPath $resolved -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $resolved).Path
        }
    }

    throw "Python 3 was not found. Install Python 3.8 or newer."
}

function Assert-SafeBatValue {
    param([string]$Name, [string]$Value)
    if ($Value -match '[\r\n&|<>%]' -or $Value.Contains([char]34)) {
        throw "$Name contains characters that are unsafe in a BAT configuration."
    }
}

$pythonPath = Resolve-PythonExecutable -Requested $PythonExe
$versionText = & $pythonPath -c "import sys; print('.'.join(map(str, sys.version_info[:3])))"
if ($LASTEXITCODE -ne 0) {
    throw "Python could not run: $pythonPath"
}
$version = [version]$versionText.Trim()
if ($version -lt [version]"3.7") {
    throw "Python 3.7 or newer is required; current version is $version."
}

if (-not $SkipMSCheck -and -not $MSInstallRoot) {
    $MSInstallRoot = $env:MS_INSTALL_ROOT
}
if (-not $SkipMSCheck -and -not $MSInstallRoot) {
    $MSInstallRoot = Read-Host "Materials Studio install root (blank skips the runtime check)"
}

$runMatScript = ""
if ($MSInstallRoot) {
    $candidate = Join-Path $MSInstallRoot "etc\Scripting\bin\RunMatScript.bat"
    if (-not (Test-Path -LiteralPath $candidate -PathType Leaf)) {
        throw "MaterialsScript runtime was not found: $candidate"
    }
    $MSInstallRoot = (Resolve-Path -LiteralPath $MSInstallRoot).Path
    $runMatScript = (Resolve-Path -LiteralPath $candidate).Path
}

if (-not $DefaultOutputRoot) {
    $suggested = Join-Path ([Environment]::GetFolderPath("MyDocuments")) "CASTEP-PL-Packages"
    $entered = Read-Host "Default output root (Enter uses $suggested)"
    $DefaultOutputRoot = if ($entered) { $entered } else { $suggested }
}

if (-not (Test-Path -LiteralPath $DefaultOutputRoot)) {
    New-Item -ItemType Directory -Path $DefaultOutputRoot -Force | Out-Null
}
$DefaultOutputRoot = (Resolve-Path -LiteralPath $DefaultOutputRoot).Path

Assert-SafeBatValue -Name "Python path" -Value $pythonPath
Assert-SafeBatValue -Name "Materials Studio path" -Value $MSInstallRoot
Assert-SafeBatValue -Name "Output path" -Value $DefaultOutputRoot

New-Item -ItemType Directory -Path $configDir -Force | Out-Null
$lines = @(
    "@echo off",
    "rem Machine-local configuration generated by Configure-CASTEP-PL-Skill.bat",
    "set `"PL_SKILL_PYTHON=$pythonPath`"",
    "set `"PL_SKILL_MS_INSTALL_ROOT=$MSInstallRoot`"",
    "set `"PL_SKILL_RUNMATSCRIPT=$runMatScript`"",
    "set `"PL_SKILL_DEFAULT_CORES=$DefaultCores`"",
    "set `"PL_SKILL_OUTPUT_ROOT=$DefaultOutputRoot`""
)
[System.IO.File]::WriteAllLines(
    $configFile,
    $lines,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host ""
Write-Host "Environment validation passed:" -ForegroundColor Green
Write-Host "  Python: $pythonPath ($version)"
if ($runMatScript) {
    Write-Host "  MaterialsScript: $runMatScript"
} else {
    Write-Warning "Materials Studio was not checked. Before submission, verify MaterialsScript, the CASTEP license, and a usable Gateway."
}
Write-Host "  Default cores: $DefaultCores"
Write-Host "  Default output root: $DefaultOutputRoot"
Write-Host "  Local configuration: $configFile"
